import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Shofi.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>


        <link
          href="https://fonts.googleapis.com/css2?family=Jost:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
        
      </head>
      <body className="antialiased" style={{ fontFamily: "'Jost', sans-serif" }}>
        {children}
      </body>
    </html>
  );
}
