// import type { Metadata } from "next";
// import "./globals.css";

// export const metadata: Metadata = {
//   title: "Shofi.",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <head>


//         <link
//           href="https://fonts.googleapis.com/css2?family=Jost:wght@100;200;300;400;500;600;700;800;900&display=swap"
//           rel="stylesheet"
//         />
//          <link
//           href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap"
//           rel="stylesheet"
//         />
        
//       </head>
//       <body className="antialiased" style={{ fontFamily: "'Jost', sans-serif" }}>
//         {children}
//       </body>
//     </html>
//   );
// }



import type { Metadata } from "next";
import Script from "next/script";
import "./globals.css";

export const metadata: Metadata = {
  title: "Shofi.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Jost:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
      </head>

      <body
        className="antialiased"
        style={{ fontFamily: "'Jost', sans-serif" }}
      >
        {children}

        {/* Chatbot Script */}
        <Script
          src="https://bot-eight-omega-34.vercel.app/chatbot.js"
          strategy="afterInteractive"
          data-org-id="usr_113610030636335898"
        />
      </body>
    </html>
  );
}
